=== StefanYlimaki/Sijaismobiili/schemas/substitution.schema.json
{
    "$schema": "https://json-schema.org/draft-06/schema",
    "title": "Substitution",
    "description": "Describes a job ad for a substitution",
    "type": "object",
    "properties": {
        "id": {
            "description": "Unique identifier for substitution",
            "type": "integer"
        },
        "date": {
            "description": "The date the job ad was left in a format that adheres to ISO 8601, for example output of Javascripts Date.toJSON()",
            "type": "string"
        },
        "title": {
            "description": "Job title",
            "type": "string"
        },
        "description": {
            "description": "Short description for the job",
            "type": "string"
        },
        "department": {
            "description": "Name of the department the job is located in",
            "type": "string"
        },
        "organisation": {
            "description": "Name of the organisation",
            "type": "string"
        },
        "location": {
            "description": "Location of the job, should resemble this format: Käsityöläiskatu 2, 20100 TURKU",
            "type": "string"
        },
        "city": {
            "description": "City or municipality where the job is located",
            "type": "string"
        },
        "coordinates": {
            "description": "Coordinates for the job, longitude and latitude in decimal degrees",
            "type": "object",
            "properties": {
                "longitude": {
                    "type":"number"
                },
                "latitude": {
                    "type":"number"
                }
            }
        },
        "timing": {
            "description": "Shift start time and duration",
            "type": "object",
            "properties": {
                "startTime": {
                    "description": "The starting time of a shift in a format that adheres to ISO 8601",
                    "type": "string"
                },
                "duration": {
                    "description": "Duration of the shift in minutes",
                    "type": "integer",
                    "exclusiveMinimum": 0
                },
                "isFlexible": {
                    "description": "Describes if the shift timing is flexible",
                    "type": "boolean"
                }
            },
            "required": [ "startTime", "duration" ]
        },
        "hourlyPay": {
            "description": "Hourly pay in euros",
            "type": "number",
            "exclusiveMinimum": 0
        },
        "benefits": {
            "description": "List of benefits like lunch or bonuses",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "contactInfo": {
            "description": "Contact info of the employer",
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                }
            }
        },
        "logo": {
            "description": "Filename of logo image",
            "type": "string"
        },
        "image": {
            "description": "URL that retrieves an image",
            "type": "string"
        }
    },
    "required": [ "id", "title", "description", "organisation", "location", "timing", "hourlyPay" ]
}

=== StefanYlimaki/Sijaismobiili/assets/data/substitutionsData_new.json
[
  {
    "id": 94,
    "date": "2023-03-28T10:09:39.901103",
    "title": "Suuhygienisti",
    "description": "Tähän tulee lyhyt kuvaus työstä",
    "department": "Keskusleikkausosasto",
    "organisation": "Pohjois-Pohjanmaan hyvinvointialue Pohde",
    "location": "Torikatu 21, 90100 OULU",
    "city": "Oulu",
    "coordinates": {
      "longitude": 25.466729956534994,
      "latitude": 65.01104770301926
    },
    "timing": {
      "startTime": "2023-04-04T10:09:39.901110",
      "duration": 480,
      "isFlexible": false
    },
    "hourlyPay": 10.14,
    "benefits": [],
    "contactInfo": {
      "email": "sijaisuudet@pohde.fi",
      "phoneNumber": "0551234567"
    },
    "logo": "",
    "image": ""
  },
  {
    "id": 42,
    "date": "2023-03-26T06:09:39.899914",
    "title": "Sosiaalityöntekijä",
    "description": "Tähän tulee lyhyt kuvaus työstä",
    "department": "Ihotautien poliklinikka",
    "organisation": "Varsinais-Suomen hyvinvointialue Varha",
    "location": "Tuulensuunkatu 6, 21100 Naantali",
    "city": "Naantali",
    "coordinates": {
      "longitude": 22.026600512353554,
      "latitude": 60.4691794883538
    },
    "timing": {
      "startTime": "2023-04-02T06:09:39.899921",
      "duration": 320,
      "isFlexible": false
    },
    "hourlyPay": 13.35,
    "benefits": [],
    "contactInfo": {
      "email": "sijaisuudet@varha.fi",
      "phoneNumber": "0551234567"
    },
    "logo": "lintunen.png",
    "image": "https://picsum.photos/400"
  },
  {
    "id": 78,
    "date": "2023-03-27T18:09:39.900736",
    "title": "Lähihoitaja",
    "description": "Tähän tulee lyhyt kuvaus työstä",
    "department": "Ihotautien poliklinikka",
    "organisation": "Varsinais-Suomen hyvinvointialue Varha",
    "location": "Tuulensuunkatu 6, 21100 Naantali",
    "city": "Naantali",
    "coordinates": {
      "longitude": 22.026600512353554,
      "latitude": 60.4691794883538
    },
    "timing": {
      "startTime": "2023-04-03T18:09:39.900743",
      "duration": 360,
      "isFlexible": false
    },
    "hourlyPay": 19.83,
    "benefits": [
      "Lounasetu"
    ],
    "contactInfo": {
      "email": "sijaisuudet@varha.fi",
      "phoneNumber": "0551234567"
    },
    "logo": "",
    "image": ""
  },
  {
    "id": 55,
    "date": "2023-03-26T19:09:39.900209",
    "title": "Lähihoitaja",
    "description": "Tähän tulee lyhyt kuvaus työstä",
    "department": "Ihotautien poliklinikka",
    "organisation": "Varsinais-Suomen hyvinvointialue Varha",
    "location": "Tuulensuunkatu 6, 21100 Naantali",
    "city": "Naantali",
    "coordinates": {
      "longitude": 22.026600512353554,
      "latitude": 60.4691794883538
    },
    "timing": {
      "startTime": "2023-04-02T19:09:39.900217",
      "duration": 360,
      "isFlexible": true
    },
    "hourlyPay": 13.92,
    "benefits": [],
    "contactInfo": {
      "email": "sijaisuudet@varha.fi",
      "phoneNumber": "0551234567"
    },
    "logo": "lintunen.png",
    "image": "https://picsum.photos/400"
  },
  {
    "id": 58,
    "date": "2023-03-26T22:09:39.900281",
    "title": "Sosiaalityöntekijä",
    "description": "Tähän tulee lyhyt kuvaus työstä",
    "department": "Yhteispäivystys",
    "organisation": "Varsinais-Suomen hyvinvointialue Varha",
    "location": "Hämeentie 11, 20521 TURKU",
    "city": "Turku",
    "coordinates": {
      "longitude": 22.295853144213755,
      "latitude": 60.454266053829656
    },
    "timing": {
      "startTime": "2023-04-02T22:09:39.900289",
      "duration": 260,
      "isFlexible": false
    },
    "hourlyPay": 15.39,
    "benefits": [
      "40€ bonus"
    ],
    "contactInfo": {
      "email": "sijaisuudet@varha.fi",
      "phoneNumber": "0551234567"
    },
    "logo": "",
    "image": ""
  },
  {
    "id": 28,
    "date": "2023-03-25T16:09:39.899588",
    "title": "Lähihoitaja",
    "description": "Tähän tulee lyhyt kuvaus työstä",
    "department": "Ihotautien poliklinikka",
    "organisation": "Varsinais-Suomen hyvinvointialue Varha",
    "location": "Käsityöläiskatu 2, 20100 TURKU",
    "city": "Turku",
    "coordinates": {
      "longitude": 22.2585894854291,
      "latitude": 60.448420880529184
    },
    "timing": {
      "startTime": "2023-04-01T16:09:39.899595",
      "duration": 270,
      "isFlexible": false
    },
    "hourlyPay": 15.12,
    "benefits": [
      "Lounasetu"
    ],
    "contactInfo": {
      "email": "sijaisuudet@varha.fi",
      "phoneNumber": "0551234567"
    },
    "logo": "lintunen.png",
    "image": "https://picsum.photos/400"
  },
  {
    "id": 7,
    "date": "2023-03-24T19:09:39.899105",
    "title": "Suuhygienisti",
    "description": "Tähän tulee lyhyt kuvaus työstä",
    "department": "Ihotautien poliklinikka",
    "organisation": "Pohjois-Pohjanmaan hyvinvointialue Pohde",
    "location": "Torikatu 21, 90100 OULU",
    "city": "Oulu",
    "coordinates": {
      "longitude": 25.466729956534994,
      "latitude": 65.01104770301926
    },
    "timing": {
      "startTime": "2023-03-31T19:09:39.899112",
      "duration": 410,
      "isFlexible": true
    },
    "hourlyPay": 15.09,
    "benefits": [],
    "contactInfo": {
      "email": "sijaisuudet@pohde.fi",
      "phoneNumber": "0551234567"
    },
    "logo": "",
    "image": ""
  },
  {
    "id": 33,
    "date": "2023-03-25T21:09:39.899707",
    "title": "Sosiaalityöntekijä",
    "description": "Tähän tulee lyhyt kuvaus työstä",
    "department": "Yhteispäivystys",
    "organisation": "Pohjois-Pohjanmaan hyvinvointialue Pohde",
    "location": "Pesätie 11, 90420 OULU",
    "city": "Oulu",
    "coordinates": {
      "longitude": 25.531864452214528,
      "latitude": 64.95636793384206
    },
    "timing": {
      "startTime": "2023-04-01T21:09:39.899715",
      "duration": 470,
      "isFlexible": true
    },
    "hourlyPay": 11.58,
    "benefits": [
      "40€ bonus"
    ],
    "contactInfo": {
      "email": "sijaisuudet@pohde.fi",
      "phoneNumber": "0551234567"
    },
    "logo": "lintunen.png",
    "image": "https://picsum.photos/400"
  },
  {
    "id": 83,
    "date": "2023-03-27T23:09:39.900849",
    "title": "Lähihoitaja",
    "description": "Tähän tulee lyhyt kuvaus työstä",
    "department": "Keskusleikkausosasto",
    "organisation": "Varsinais-Suomen hyvinvointialue Varha",
    "location": "Käsityöläiskatu 2, 20100 TURKU",
    "city": "Turku",
    "coordinates": {
      "longitude": 22.2585894854291,
      "latitude": 60.448420880529184
    },
    "timing": {
      "startTime": "2023-04-03T23:09:39.900856",
      "duration": 290,
      "isFlexible": true
    },
    "hourlyPay": 14.24,
    "benefits": [],
    "contactInfo": {
      "email": "sijaisuudet@varha.fi",
      "phoneNumber": "0551234567"
    },
    "logo": "lintunen.png",
    "image": "https://picsum.photos/400"
  },
  {
    "id": 29,
    "date": "2023-03-25T17:09:39.899615",
    "title": "Sairaanhoitaja",
    "description": "Tähän tulee lyhyt kuvaus työstä",
    "department": "Yhteispäivystys",
    "organisation": "Varsinais-Suomen hyvinvointialue Varha",
    "location": "Käsityöläiskatu 2, 20100 TURKU",
    "city": "Turku",
    "coordinates": {
      "longitude": 22.2585894854291,
      "latitude": 60.448420880529184
    },
    "timing": {
      "startTime": "2023-04-01T17:09:39.899623",
      "duration": 360,
      "isFlexible": true
    },
    "hourlyPay": 11.66,
    "benefits": [],
    "contactInfo": {
      "email": "sijaisuudet@varha.fi",
      "phoneNumber": "0551234567"
    },
    "logo": "",
    "image": ""
  },
  {
    "id": 87,
    "date": "2023-03-28T03:09:39.900944",
    "title": "Röntgenhoitaja",
    "description": "Tähän tulee lyhyt kuvaus työstä",
    "department": "Keskusleikkausosasto",
    "organisation": "Varsinais-Suomen hyvinvointialue Varha",
    "location": "Tuulensuunkatu 6, 21100 Naantali",
    "city": "Naantali",
    "coordinates": {
      "longitude": 22.026600512353554,
      "latitude": 60.4691794883538
    },
    "timing": {
      "startTime": "2023-04-04T03:09:39.900951",
      "duration": 330,
      "isFlexible": true
    },
    "hourlyPay": 18.74,
    "benefits": [],
    "contactInfo": {
      "email": "sijaisuudet@varha.fi",
      "phoneNumber": "0551234567"
    },
    "logo": "lintunen.png",
    "image": "https://picsum.photos/400"
  },
  {
    "id": 89,
    "date": "2023-03-28T05:09:39.900989",
    "title": "Hammashoitaja",
    "description": "Tähän tulee lyhyt kuvaus työstä",
    "department": "Yhteispäivystys",
    "organisation": "Varsinais-Suomen hyvinvointialue Varha",
    "location": "Tuulensuunkatu 6, 21100 Naantali",
    "city": "Naantali",
    "coordinates": {
      "longitude": 22.026600512353554,
      "latitude": 60.4691794883538
    },
    "timing": {
      "startTime": "2023-04-04T05:09:39.900996",
      "duration": 280,
      "isFlexible": false
    },
    "hourlyPay": 12.39,
    "benefits": [],
    "contactInfo": {
      "email": "sijaisuudet@varha.fi",
      "phoneNumber": "0551234567"
    },
    "logo": "",
    "image": ""
  },
  {
    "id": 22,
    "date": "2023-03-25T10:09:39.899448",
    "title": "Suuhygienisti",
    "description": "Tähän tulee lyhyt kuvaus työstä",
    "department": "Yhteispäivystys",
    "organisation": "Varsinais-Suomen hyvinvointialue Varha",
    "location": "Tuulensuunkatu 6, 21100 Naantali",
    "city": "Naantali",
    "coordinates": {
      "longitude": 22.026600512353554,
      "latitude": 60.4691794883538
    },
    "timing": {
      "startTime": "2023-04-01T10:09:39.899455",
      "duration": 280,
      "isFlexible": true
    },
    "hourlyPay": 19.39,
    "benefits": [],
    "contactInfo": {
      "email": "sijaisuudet@varha.fi",
      "phoneNumber": "0551234567"
    },
    "logo": "lintunen.png",
    "image": "https://picsum.photos/400"
  },
  {
    "id": 59,
    "date": "2023-03-26T23:09:39.900304",
    "title": "Sosiaalityöntekijä",
    "description": "Tähän tulee lyhyt kuvaus työstä",
    "department": "Keskusleikkausosasto",
